[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]

[env]
TERM = "xterm-256color"

[scrolling]
history = 2000

[window]
opacity = 0.8
decorations = "none"
blur = true
dynamic_padding = true

[window.padding]
x = 0
y = 0

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"

